# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'GQSecretImageDemo' do
pod 'GQSecretImage', :path => '../'
end
target 'GQSecretImageDemoTests' do

end
